from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

b1 = KeyboardButton('/help')
b2 = KeyboardButton('/advice')
b3 = KeyboardButton('/introduction')
t1 = InlineKeyboardButton('1️⃣', callback_data='btn_1')
t2 = InlineKeyboardButton('2️⃣', callback_data='btn_2')
t3 = InlineKeyboardButton('3️⃣', callback_data='btn_3')
t4 = InlineKeyboardButton('4️⃣', callback_data='btn_4')
t5 = InlineKeyboardButton('5️⃣', callback_data='btn_5')
t6 = InlineKeyboardButton('6️⃣', callback_data='btn_6')
t7 = InlineKeyboardButton('7️⃣', callback_data='btn_7')
t8 = InlineKeyboardButton('8️⃣', callback_data='btn_8')
t9 = InlineKeyboardButton('9️⃣', callback_data='btn_9')
t10 = InlineKeyboardButton('1️⃣0️⃣', callback_data='btn_10')
t11 = InlineKeyboardButton('1️⃣1️⃣', callback_data='btn_11')
quiz = KeyboardButton('/quiz')
send_file = KeyboardButton('/send_the_task')
cancel = KeyboardButton('/cancel')
checker123 = KeyboardButton('/check_the_task')


checker_button = ReplyKeyboardMarkup(resize_keyboard=True)
task = ReplyKeyboardMarkup(resize_keyboard=True)
kb_client = ReplyKeyboardMarkup(resize_keyboard=True)
lesson_btn = InlineKeyboardMarkup().row(t1, t2, t3).row(t4, t5, t6).row(t7, t8, t9).row(t10, t11)
task.row(quiz, send_file).add(cancel)
kb_client.add(b1).add(b2).insert(b3)
checker_button.add(checker123)